name: deep-learning
channels:
  - defaults
dependencies:
  - python==3.10.6
  - pillow==9.0.1
  - numpy
  - pyyaml
  - matplotlib
  - jupyter
  - pytest
  - tqdm
  - jupyter
  - pip
  - pandas
  - scikit-learn
  - transformers
  - captum
  - timm



