# log dir 

# model setting
#pretrained: weights/spsl_fs.pth   # path to a pre-trained model, if using one
#pretrained: weights/spsl_fs.pth
#model_name: spsl   # model name

#backbone setting
backbone_config:
  mode: original
  num_classes: 2
  inc: 4
  dropout: false
