model_type: 'xception'
data_root_dir: "../../DF40/DeepfakeBench_DF40/deepfakes_detection_datasets/DF40/MidJourney"
training_ds: "FS"
testing_ds: "MJ"
weights_path: "../../DF40/DeepfakeBench_DF40/weights/xception_fs.pth"
