# MODEL
model_type: 'xception'
weights_path: "/Users/adrian.prayoga/omscs/deep_learning/deep-learning-project/weights/xception_fs.pth"
training_ds: "FS"
testing_ds: "MJ"

# DATA
#data_root_dir: "/Users/adrian.prayoga/omscs/deep_learning/deep-learning-project/dataset/starganv2"
#data_root_dir: "/Users/adrian.prayoga/omscs/deep_learning/deep-learning-project/dataset/midjourneyoriginal"
data_root_dir: "/Users/adrian.prayoga/omscs/deep_learning/deep-learning-project/dataset/midjourney"
saliency_data_root_dir: "/Users/adrian.prayoga/omscs/deep_learning/deep-learning-project/dataset/midjourney_saliency"


